### ISSUE TITLE
verify credits for 1.0.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#10]
Verify credits for this sim. Currently the same as Graphing Lines, but @amanda-phet has been added as primary designer.

**Comment by pixelzoom** [comment]
@amanda-phet Below are the current credits.  Let me know if there are any changes. Assign back to me, and I'll have @phet-steele review QA credits during RC testing.

![screenshot_195](https://cloud.githubusercontent.com/assets/3046552/24616676/0ae7c0de-184f-11e7-9104-e0a7d1a4d458.png)

**Comment by amanda-phet** [comment]
Looks good to me.

**Comment by pixelzoom** [comment]
@phet-steele Looks like you're getting close to completing RC test https://github.com/phetsims/tasks/issues/852.  Let me know who to add to the QA credits.

**Comment by amanda-phet** [comment]
Can you remove my name from "team" for this sim since it's alreayd listed as lead?

**Comment by pixelzoom** [comment]
@amanda-phet removed from team credits in above commit.

**Comment by pixelzoom** [comment]
@phet-steele  just indicate the QA changes here as a comment, rather than editing the file yourself. I have some formatting (line breaks) to sort out in the credits, easier if I handle it.

**Comment by phet-steele** [comment]
@pixelzoom we are missing Alex Dornan, Ethan Johnson, and Maggie Wiseman.

**Comment by pixelzoom** [comment]
QA credits update.  Here's the final credits, as they will appear in 1.0.0 and master:

![screenshot_279](https://user-images.githubusercontent.com/3046552/27143796-cbe835f4-50ec-11e7-840d-6a503e369c5b.png)
