### ISSUE TITLE
create graphing-slope-intercept-screenshot.png

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#11]
@amanda-phet please send me a screenshot showing how you would like the sim's thumbnail and screenshot to appear on the PhET website. You can use [1.0.0-dev.5](http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.5/graphing-slope-intercept_en.html). I'll handle creation of the final screenshot.

**Comment by pixelzoom** [comment]
@amanda-phet Graphing Slope-Intercept is now in RC testing, so we'll need this screenshot very soon.

**Comment by amanda-phet** [comment]
The current screenshot for Graphing Lines is the slope-intercept screen... The sims are also very similar in appearance, so I'm not sure what to do yet. 

I'm leaning toward changing the Graphing Lines screenshot to point-slope, but the differences are still going to be pretty subtle, so my other idea is to take a screenshot of the game for Graphing Slope-Intercept. 

Any ideas @pixelzoom @phet-steele @ariel-phet ?

**Comment by amanda-phet** [comment]
Two game screen options: 
<img width="959" alt="screen shot 2017-04-11 at 11 35 38 am" src="https://cloud.githubusercontent.com/assets/7852916/24922299/162cc482-1eab-11e7-8857-ef0042c110c7.png">

<img width="960" alt="screen shot 2017-04-11 at 11 37 48 am" src="https://cloud.githubusercontent.com/assets/7852916/24922388/5778bf90-1eab-11e7-8ce3-3744a58cdd35.png">

**Comment by pixelzoom** [comment]
Your call @amanda-phet.  

FYI, I'm not sure how we would go about changing the screenshot for Graphing Lines without republishing it.  There's probably a manual way to do it, but certainly nothing in our build tool.

**Comment by phet-steele** [comment]
@amanda-phet I believe our standard is to not show answers to a game challenge in our screenshot (with the exception of Arithmetic and Fraction Matcher). I think this leaves us with doing a screenshot of an unanswered game challenge (sounds boring) or changing the current Graphing Lines screenshot. @pixelzoom correctly stated we will have to republish in that case; the manual way of changing the screenshot is not ideal (@mattpen stated if we do it manually, the old screenshot will still be cached and visible for a month... 😮). Besides, republishing is the easiest way to keep the source code and production version the same.

**Comment by pixelzoom** [comment]
@amanda-phet FYI, Graphing Lines is on deck for republishing once https://github.com/phetsims/graphing-lines/issues/72 has been verified.  So if you want to change it's screenshot, we can - please create an issue if you do.   But as @phet-steele said, there will be a period of time where the screenshots for Graphing Lines and Graphing Slope-Intercept both show the slope-intercept screen.

**Comment by amanda-phet** [comment]
Thanks @pixelzoom I realized the same thing. I would like to propose the following two screenshots. 

Graphing Slope-Intercept: Parallel lines work well for this screen, but in order to minimize some confusing with the previous Graphing lines sim I have changed the lines to have negative slopes. 
<img width="946" alt="screen shot 2017-04-11 at 12 55 44 pm" src="https://cloud.githubusercontent.com/assets/7852916/24925784/996169d8-1eb6-11e7-93b9-4471083c7fdf.png">


Graphing Lines: Uses the point-slope screen,  and shows a system of equations with a clear intersection point. 
<img width="944" alt="screen shot 2017-04-11 at 12 55 04 pm" src="https://cloud.githubusercontent.com/assets/7852916/24925827/bc183060-1eb6-11e7-85f2-1270137b357b.png">

Open to feedback from anyone mentioned earlier.

**Comment by pixelzoom** [comment]
@amanda-phet I defer the decision to you.  

But you might want to scale both of those images down, and see how they look in context.   Particularly how Graphing Lines and Graphing Slope-Intercept thumbnails look when positioned right next to each other in (e.g.) https://phet.colorado.edu/en/simulations/category/by-device/ipad-tablet.   

Here's how the Graphing Lines screenshot currently looks once it's scaled down:

![screenshot_208](https://cloud.githubusercontent.com/assets/3046552/24926391/9f1ea1e0-1eb8-11e7-8cd5-9703fa15e80a.png)

![screenshot_209](https://cloud.githubusercontent.com/assets/3046552/24926394/a376f59e-1eb8-11e7-9ba5-8462ebe52816.png)

**Comment by amanda-phet** [comment]
@pixelzoom are you saying the two screenshots look too similar? There isn't a great way around this, I don't think. The screenshots for States of Matter and States of Matter: Basics look nearly identical and I think it's the only option for these sims- unless we do something unconventional and show a lot of saved lines that make a distinguishable "image" on the graph.

**Comment by pixelzoom** [comment]
I'm not inferring anything about the specific screenshots that you proposed.  I'm saying that evaluating whether they look too similar needs to be done in context.

**Comment by ariel-phet** [comment]
@pixelzoom @amanda-phet - should we perhaps consider a different background color for graphing-slope-intercept?

**Comment by ariel-phet** [comment]
ie could just be white

**Comment by amanda-phet** [comment]
Thanks @ariel-phet I like that idea a lot. @pixelzoom is going to try another color and publish a version for us to look at.

**Comment by pixelzoom** [comment]
+1 for trying another background color.  Since the background color is the dominate color in the thumbnail, I think that will really make it much easier to differentiate between the 2 sims.

@amanda-phet and I discussed, and we're going to try the background color from Unit Rates "Shipping" screen, `'rgb( 226, 255, 249 )'`.    

Since we're in RC test and dev test for GSI and GL respectively, it's unfortunate that this will require a nontrivial code change to both sims.  But I think it's for the best, so I'll proceed.

**Comment by pixelzoom** [comment]
Here's a dev version with the new background color, `'rgb( 226, 255, 249 )'`:

http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.7/graphing-slope-intercept_en.html

Compare to the old color (light yellow): 

http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.6/graphing-slope-intercept_en.html

@amanda-phet @ariel-phet please review.

**Comment by ariel-phet** [comment]
I think it looks great!

**Comment by pixelzoom** [comment]
Btw... If we change the background color like this, do we really need to change the Graphing Lines screenshot?

**Comment by pixelzoom** [comment]
Here's the proposed thumbnail for Graphing Slope-Intercept shown next to the existing Graphing Lines thumbnail:

![screenshot_208](https://cloud.githubusercontent.com/assets/3046552/24971228/759f7f9e-1f74-11e7-804d-f37b88cbb4d3.jpg)

**Comment by pixelzoom** [comment]
@amanda-phet RC testing had not begun yet, so I put that process on hold until we close this issue.   So top-priority since this is now blocking RC testing.

**Comment by amanda-phet** [comment]
The color looks great. No need to change the GL screenshot, but I wouldn't do two parallel lines for both, so let's just do one line (something like this): 

![screen shot 2017-04-12 at 12 46 50 pm](https://cloud.githubusercontent.com/assets/7852916/24974113/5e822b18-1f7e-11e7-9de7-607b16094607.png)

**Comment by amanda-phet** [comment]
I just remembered I turned off slope because i was trying other things.. use this instead (with slope on) and a less steep line: 

![screen shot 2017-04-12 at 12 50 56 pm](https://cloud.githubusercontent.com/assets/7852916/24974252/cc764dca-1f7e-11e7-933d-074561a65a77.png)

Thanks @pixelzoom !

**Comment by pixelzoom** [comment]
Since I don't have a retina iPad, @phet-steele has volunteered to create the screenshot.  See https://github.com/phetsims/graphing-slope-intercept/issues/11#issuecomment-293673371 for configuration.

**Comment by phet-steele** [comment]
@pixelzoom screenshot added to both branches. Feel free to close.

**Comment by pixelzoom** [comment]
Reviewed, screenshots look great, thanks @phet-steele! Closing.
