### ISSUE TITLE
Game timer does not count up during a level

### ISSUE THREAD

**Issue by phet-steele** [phetsims/graphing-slope-intercept#12]
Enable the game timer and enter a level. It will stay at 0:00 throughout the level. Upon completion of a level, the timer WILL however present the player with a correct time. 👍 

<img width="1456" alt="screen shot 2017-04-05 at 11 15 25 am" src="https://cloud.githubusercontent.com/assets/5863899/24717917/5dda489a-19f1-11e7-88a2-cd1cd2aa264e.png">

Seen on macOS 10.12.4 Chrome. For phetsims/tasks/issues/812.
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.6/graphing-slope-intercept_en.html
Version: 1.0.0-dev.6 2017-04-05 15:13:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1456x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"f7720d0e","branch":"HEAD"},"babel":{"sha":"ff109163","branch":"master"},"brand":{"sha":"054ca5c3","branch":"master"},"chipper":{"sha":"52c3aa33","branch":"HEAD"},"dot":{"sha":"569939e1","branch":"HEAD"},"graphing-lines":{"sha":"2333ca01","branch":"master"},"graphing-slope-intercept":{"sha":"104882e0","branch":"master"},"joist":{"sha":"c5a63104","branch":"HEAD"},"kite":{"sha":"81166ce9","branch":"HEAD"},"phet-core":{"sha":"c5c6c2a8","branch":"HEAD"},"phetcommon":{"sha":"85801e7b","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"49e17a1d","branch":"HEAD"},"scenery-phet":{"sha":"6213dc27","branch":"HEAD"},"sherpa":{"sha":"3255de0f","branch":"HEAD"},"sun":{"sha":"bffd225e","branch":"HEAD"},"tandem":{"sha":"a668abd5","branch":"HEAD"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by phet-steele** [comment]
@pixelzoom I can confirm this is a problem in the current master of graphing-lines

**Comment by pixelzoom** [comment]
I see this same problem in master for balancing-chemical-equations and reactants-products-and-leftovers.   My first thought is that it may be related to the conversion from PropertySet to Property.

**Comment by pixelzoom** [comment]
This is indeed a general problem with vegas.GamerTimer, see https://github.com/phetsims/vegas/issues/57.

**Comment by pixelzoom** [comment]
Fixed over in https://github.com/phetsims/vegas/issues/57.  @phet-steele If things look good there, you can close this issue.

**Comment by phet-steele** [comment]
https://github.com/phetsims/vegas/issues/57 is resolved, closing.
