### ISSUE TITLE
Best time does not clear with a Reset All

### ISSUE THREAD

**Issue by phet-steele** [phetsims/graphing-slope-intercept#13]
Best time will still be visible under each level (with the timer enabled) even after a Reset All. The old best time will also still be shown on the reward screen (unless you beat your time). This is present in graphing-slope-intercept and graphing-lines.

![gsi01](https://cloud.githubusercontent.com/assets/5863899/24720091/2fb25dc4-19f9-11e7-8d5b-0231fa032cef.gif)

Seen on macOS 10.12.4 Chrome. For phetsims/tasks#812.
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.6/graphing-slope-intercept_en.html
Version: 1.0.0-dev.6 2017-04-05 15:13:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1456x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"f7720d0e","branch":"HEAD"},"babel":{"sha":"ff109163","branch":"master"},"brand":{"sha":"054ca5c3","branch":"master"},"chipper":{"sha":"52c3aa33","branch":"HEAD"},"dot":{"sha":"569939e1","branch":"HEAD"},"graphing-lines":{"sha":"2333ca01","branch":"master"},"graphing-slope-intercept":{"sha":"104882e0","branch":"master"},"joist":{"sha":"c5a63104","branch":"HEAD"},"kite":{"sha":"81166ce9","branch":"HEAD"},"phet-core":{"sha":"c5c6c2a8","branch":"HEAD"},"phetcommon":{"sha":"85801e7b","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"49e17a1d","branch":"HEAD"},"scenery-phet":{"sha":"6213dc27","branch":"HEAD"},"sherpa":{"sha":"3255de0f","branch":"HEAD"},"sun":{"sha":"bffd225e","branch":"HEAD"},"tandem":{"sha":"a668abd5","branch":"HEAD"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by pixelzoom** [comment]
Note to self: check this in BCE and RPAL too.

**Comment by pixelzoom** [comment]
Not a problem in BCE or RPAL.

**Comment by pixelzoom** [comment]
This has been a problem in graphing-lines forever, thanks for finding it @phet-steele.  It's fixed in the above commit. Please verify in master.

**Comment by phet-steele** [comment]
No problem, fixed.
