### ISSUE TITLE
Test Issue: Clock not working

### ISSUE THREAD

**Issue by maggiewiseman** [phetsims/graphing-slope-intercept#14]
Test device: Macbook Air

Operating System: osx 10.12.3

Browser: Chrome

Problem description: Clicked to show timer. When I started the line 1 graph the timer at the top of the screen stayed at 0:00.

Steps to reproduce: 

1. Enter line-game screen. 
2. Click on timer. 
3. Click on Level 1. 
4. Observed that timer was not incrementing.

Severity:

Screenshots:

Related to: phetsims/tasks/issues/812 

Troubleshooting information (do not edit):
Name: ‪Graphing Slope-Intercept‬
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.5/graphing-slope-intercept_en.html
Version: 1.0.0-dev.5 2017-03-25 07:48:26 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1274x642
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"ca937302","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"a3f44a2f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"graphing-lines":{"sha":"2333ca01","branch":"master"},"graphing-slope-intercept":{"sha":"1907b3de","branch":"master"},"joist":{"sha":"e9e4056a","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"e24681a5","branch":"master"},"scenery-phet":{"sha":"e404e619","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"28d0127c","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by phet-steele** [comment]
@maggiewiseman Thanks, this is fixed in the latest dev here http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.7/graphing-slope-intercept_en.html. Can you verify and close?

**Comment by maggiewiseman** [comment]
Fixed. Thank you, developer.
