### ISSUE TITLE
in iFrame line games pointers can be dragged off screen to the right and are not recoverable

### ISSUE THREAD

**Issue by maggiewiseman** [phetsims/graphing-slope-intercept#16]
Test device: Mac Airbook

Operating System: OSx 10.11.5

Browser: Chrome

Problem description:
When playing the line game the pointer tools can be dragged off the screen to the right.  If the user doesn't drag them back right away, they cannot be seen to be clicked on and dragged back into the iframe

Steps to reproduce:
1. Open the sim in an iFrame
2. Navigate to a line game
3. Start the game
4. Click on a pointer tool and drag to the right until you can't see it.  
5. Let go of the mouse button 
6. Try click in the same spot will not recover the tool.  

![screen shot 2017-04-16 at 3 06 01 pm](https://cloud.githubusercontent.com/assets/17385784/25073506/3870c0de-22b6-11e7-85a9-1977b2e3daf5.png)

Related to: phetsims/tasks#815

Troubleshooting information (do not edit):
Name: ‪Graphing Slope-Intercept‬
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-rc.1/graphing-slope-intercept_en.html
Version: 1.0.0-rc.1 2017-04-12 19:48:25 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1381x722
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"81919d26","branch":"HEAD"},"babel":{"sha":"fdde4356","branch":"master"},"brand":{"sha":"054ca5c3","branch":"HEAD"},"chipper":{"sha":"36dc0e55","branch":"HEAD"},"dot":{"sha":"a0c5770e","branch":"HEAD"},"graphing-lines":{"sha":"032bc04e","branch":"HEAD"},"graphing-slope-intercept":{"sha":"a851237a","branch":"HEAD"},"joist":{"sha":"91516011","branch":"HEAD"},"kite":{"sha":"81166ce9","branch":"HEAD"},"phet-core":{"sha":"c5c6c2a8","branch":"HEAD"},"phetcommon":{"sha":"68053a7d","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"17b5a7e4","branch":"HEAD"},"scenery-phet":{"sha":"8ea5852c","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"50c6a1d0","branch":"HEAD"},"tandem":{"sha":"18703f2f","branch":"HEAD"},"vegas":{"sha":"3c3561d2","branch":"HEAD"},"vibe":{"sha":"49fdbe7d","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
I reproduced this problem.  It's also a problem in Graphing Lines.  These drag bounds need to be adjusted in Challenge.js:

```js
62 this.pointTool1 = new PointTool( new Vector2( 1.5, -10.5 ), 'up', this.graph.lines, new Bounds2( -13, -13, 14, 15 ) );
63 this.pointTool2 = new PointTool( new Vector2( 7, -13 ), 'down', this.graph.lines, new Bounds2( -13, -16, 14, 12 ) );
```

**Comment by pixelzoom** [comment]
Fixed in graphing-lines master.  This will require a "spot check" in 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
@maggiewiseman @phet-steele Can one of you please verify this in master?  Test it in graphing-lines, since it's not specific to graphing-slope-intercept.  If it looks OK, please close this issue, since the next RC of graphing-slope-intercept will be built with graphing-lines-master.  Thanks.

**Comment by maggiewiseman** [comment]
Tested in graphing-lines master, but not in an iFrame specifically.   Looks like the ability to drag the pointer off the screen happened in the previous non-iFrame version of graphing-lines an is now doesn't let you drag the pointer all the way off the screen.  The pointer is still recoverable in graphing-lines master.  Closing this issue.
