### ISSUE TITLE
pick up the fix for web audio for 1.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#17]
Related to RC test phetsims/tasks#815.

In https://github.com/phetsims/tasks/issues/815#issuecomment-294937398, @phet-steele said:
> @pixelzoom, as a reminder before rc.2, this sim will need to pick up changes from phetsims/vibe#30 (of which rc.1 currently suffers from).

and:
> Actually, it may need the other two patches from #818?

Apparently there was a change to the audio API that broke all sims on Safari, and was recently fixed and patched.  Unfortunately that fix was made after I created the 1.0 release branch, so the bug is still present in 1.0.0-rc.1.   So we'll need to figure out how to patch this, or we'll need to do another full RC test with master branches of the fixed repo(s).

**Comment by pixelzoom** [comment]
Related to RC test https://github.com/phetsims/tasks/issues/816

**Comment by pixelzoom** [comment]
Looks like this may be a moot issue, because I need to update to scenery-master to pick up https://github.com/phetsims/graphing-lines/issues/75#issuecomment-294995870.   So perhaps we'll just update everything to master and do another complete RC test.  @phet-steele how do you feel about that?

**Comment by phet-steele** [comment]
> @phet-steele how do you feel about that?

I'm not opposed.

**Comment by phet-steele** [comment]
@jonathanolson would grabbing master of everything be sufficient to get all three patches?

**Comment by pixelzoom** [comment]
[4/18/17, 5:13:39 PM] Chris Malley: Presumably if I use current master of all repos, I'll have the web audio fix.
[4/18/17, 5:14:16 PM] Jonathan Olson: Correct, master should have all of those changes

**Comment by pixelzoom** [comment]
Next RC will be built off of master repos.  And the same shas will be used for next test version (dev or RC) of Graphing Lines.

**Comment by pixelzoom** [comment]
The plan is to build the next RC off of master, so closing.
