### ISSUE TITLE
layout of level-selection buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#18]
@kathy-phet and @amanda-phet discussed the layout of the level-selection buttons on the Line Game screen.  

It currently looks like this:

![screenshot_220](https://cloud.githubusercontent.com/assets/3046552/25244154/d2a9dfd8-25bc-11e7-81e5-f2eaf93368f3.png)

@kathy-phet would like to see the buttons in 1 row:

![screenshot_221](https://cloud.githubusercontent.com/assets/3046552/25244168/dd9e0e8c-25bc-11e7-8c49-c99b15c426b5.png)

A couple of notes:

(1) This change is normally relatively easy. But we are unfortunately now in RC test, so this change will be somewhat expensive.

(2) Changing the layout of the buttons is trivial, and could be patched into the RC branch. 

(3) Changing the vertical spacing between the title ("Choose You Level") and the buttons is _not_ trivial, and involves touching several files.  It will therefore require starting over with RC testing.

(4) A decision needs to be made immediately, so "top priority".

**Comment by pixelzoom** [comment]
Notes to self, if we decide to change to a single row:

(1) To put buttons in one row (1 file affected):

• change `GSILineGameScreenView` to:

```js
var levelImages = [ [ level1Image, level3Image, level5Image, level6Image ] ];
```

(2) To adjust vertical space between title and buttons (3 files affected):

• add `options.titleYSpacing: 50` to `BaseGameScreenView` and `SettingsNode`
• replace `50` with `options.titleYSpacing` at line 50 of `SettingsNode`
• specify the desired value for `options.titleYSpacing` in `GSILineGameScreenView`

**Comment by amanda-phet** [comment]
@kathy-phet for reference, you mentioned Balancing Act, and here is how that screen compares. The grass really changes the appearance, so for BA, it makes the most sense to be horizontal. I could go either way for this sim, but would want the spacing between "choose your level" and the buttons to be larger. 

<img width="848" alt="screen shot 2017-04-20 at 11 29 04 am" src="https://cloud.githubusercontent.com/assets/7852916/25246878/54e29b6c-25c6-11e7-8d1a-30a099f33f20.png">

**Comment by amanda-phet** [comment]
Talked with @kathy-phet and I think we should go with the horizontal layout, but not change any spacing. So, going with this route that Chris mentioned above: 
>(2) Changing the layout of the buttons is trivial, and could be patched into the RC branch.

**Comment by pixelzoom** [comment]
Change completed in master and 1.0 branches.  

@phet-steele FYI this will appear in the next RC.

**Comment by pixelzoom** [comment]
Tagging https://github.com/phetsims/tasks/issues/815, since this was changed during RC testing.

**Comment by pixelzoom** [comment]
Closing this issue since it will now be shown in the RC test task.
