### ISSUE TITLE
challenge requirements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#2]
Challenge factories codify the challenge requirements for each game level.  

Javascript code for Graphing Lines “challenge factories” are here:
https://github.com/phetsims/graphing-lines/tree/master/js/linegame/model
The files of interest are ChallengeFactory1.js through ChallengeFactory6.js, where the number corresponds to the game level.

We'll need new challenge requirements for this sim, which excludes point-slope challenges. Depending on the specification, I will either (a) modify the existing challenge factories, or (b) create new challenge factories - whichever is most maintainable.

@amanda-phet I have the basic sim up and running. Further work is blocked until the challenge requirements are specified.

**Comment by pixelzoom** [comment]
Having the same number of levels (6) in both sims would certainly simplify things.  But it's not a requirement.   If we keep the levels the same, there are zero changes required to the view, the "Line Game" screen can be used as-is.  If we change the number of levels, then most of the work will involve specifying which icon to use for which level.

**Comment by amanda-phet** [comment]
I've started a doc here: https://docs.google.com/document/d/1ztSRN1YE1BIGI1rsCBnZXzZQYvelSFySp4sDHPh2OJs/edit# 

I am going through the challenge factories and figuring out how to modify them. I will let you know when I have a good idea for all six levels.

**Comment by pixelzoom** [comment]
@amanda-phet The document that you started has no mention of the "Slope" screen, which I thought was part of this sim (see my estimate in https://github.com/phetsims/graphing-lines/issues/66#issuecomment-283968577).  Do you not want the "Slope" screen in this sim?

**Comment by amanda-phet** [comment]
It is an incomplete document, but I wasn't sure about that particular screen and the final decision. I don't have a strong opinion either way. There aren't any game challenges based on the slope screen in either game which is why I am not sure about the best way to go.

**Comment by pixelzoom** [comment]
OK, I'll leave "Slope" in for now.

**Comment by pixelzoom** [comment]
Tracking whether to include Slope screen in https://github.com/phetsims/graphing-slope-intercept/issues/3.

**Comment by amanda-phet** [comment]
Discussed with @pixelzoom over Skype today. New challenges are specified in the design doc mentioned above.

**Comment by pixelzoom** [comment]
I have everything I need to continue working on this.

**Comment by pixelzoom** [comment]
Email conversation:

I asked:
> For place-the-points in Level 4, where we have slope=0 and slope=undefined, do you want to include zero as a possible random intercept?

@amanda-phet replied:
> No I don’t. Thanks for asking. If we had more of those questions I’d want to include 0, but since it’s just a few questions I’d like it to be [-10,-1], [1,10].

**Comment by pixelzoom** [comment]
Graphing Slope-Intercept is feature complete.  @amanda-phet please verify that the challenges match the specification in this dev version:

http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.1/graphing-slope-intercept_en.html

Query parameters that you may find useful:

* `showAnswers` - shows answers in the game
* `gameDebug` - adds "Skip" and "Replay" buttons to the game
* `showReward` - shows reward at end of game, regardless of score
* `shuffleChallenges=false` - shows challenges in the order that they are described in the specification, instead of randomly shuffling them

Here's a URL with all of the above query parameters:

http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.1/graphing-slope-intercept_en.html?showAnswers&gameDebug&showReward&shuffleChallenges=false

If you'd like to inspect the code for the challenge factories, the Javascript files are `GSIChallengeFactory1.js`,..., and they live in:

https://github.com/phetsims/graphing-slope-intercept/tree/master/js/linegame/model

Challenges are numbered in the code with a comment, and the numbers correspond to the design document. E.g.:

```js
// CHALLENGE 1: Graph-the-Line, slope-intercept form, slope or intercept variable (random choice)
``

**Comment by amanda-phet** [comment]
These look pretty great. 

The only one I'm unsure about is level 3 challenge #6. 

It's possible to have a fractional y-intercept, and on the one hand it's a nice challenge, but on the other it is confusing in a sim that is stressing slope-intercept form and yet the points are constrained to integers... so it's impossible to place a point at the y-intercept. That bugs me. It's not impossible to answer, but seems to stretch the learning goals. 

Since this particular challenge was made from a slope and a random point, we should probably re-work the logic so that it has an integer y-intercept. Can you do that with the same line of code that is in challenge #5 (line 124) but also make sure the two challenges have unique lines?

**Comment by pixelzoom** [comment]
@amanda-phet asked:
> Can you do that with the same line of code that is in challenge #5 (line 124) but also make sure the two challenges have unique lines?

Yes, I can make it so.

**Comment by pixelzoom** [comment]
@amanda-phet I made the change and updated the design doc.  

One caveat is that challenges 5 & 6 will be unique lines, but it's possible that they may have the same y-intercept.  It doesn't sound like that will be a problem, just wanted you to know.

Gotta run now, but I'll get you a dev version "soon".

**Comment by pixelzoom** [comment]
@amanda-phet Here's a dev version for verifying the change to challenge 6 in level 3:

http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.2/graphing-slope-intercept_en.html?showAnswers&shuffleChallenges=false&gameDebug

**Comment by amanda-phet** [comment]
I think it would be fine to have the same y-intercept for two challenges in a row. 

The change looks good to me.
