### ISSUE TITLE
disable showAnswers in production versions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#20]
phetsims/joist#406 is a prerequisite to this.

This will be addressed first in graphing-lines by https://github.com/phetsims/graphing-lines/issues/67.  Then we'll need to republish this sim.

**Comment by pixelzoom** [comment]
Addressed in phetsims/graphing-lines#67. Awaiting publication.

**Comment by KatieWoe** [comment]
Confirmed 1.1.0-rc.1
