### ISSUE TITLE
title case

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-slope-intercept#21]
>@KatieWoe please continue to make issues, but assign them to the lead designer for final review.

For phetsims/tasks/issues/953
Same case as phetsims/graphing-lines/issues/90
@ariel-phet in case this task should be ended.

**Comment by pixelzoom** [comment]
Oh, I see -- graphing-slope-intercept uses the same code base as graphing-slope, so it has the same "case" issues as graphing-lines.  Got it.    My comments are the same as for phetsims/graphing-lines/issues/90, and it will be @amanda-phet's call.

**Comment by pixelzoom** [comment]
The checkboxes in question are being changed to use icons instead of text (see https://github.com/phetsims/graphing-lines/issues/91), so this issue is now irrelevant.  Closing.
