### ISSUE TITLE
revise screenshots for 1.1.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#22]
The changes in phetsims/graphing-lines#91 and phetsims/graphing-lines#94 have changed how this sim looks, so screenshots will need to be revised.

Assigning to @amanda-phet and @KatieWoe, since they're working on a similar issue for graphing-lines.

**Comment by pixelzoom** [comment]
@KatieWoe asked:
> Though, did the game screen change?

_Line Game_ screen should not have any changes.

**Comment by KatieWoe** [comment]
In that case I will only replace the slope-intercept screen screenshot.

**Comment by amanda-phet** [comment]
the main screenshot looks good. I agree, no need to replace the others too.

**Comment by KatieWoe** [comment]
@amanda-phet @pixelzoom the above commit should do it.  Double check and close if acceptable.

**Comment by pixelzoom** [comment]
Perfecto! Closing.

**Comment by pixelzoom** [comment]
Reopening.   Per the [new sim master checklist](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md), screenshots are supposed to be "2048x1344, PNG, 32-bit color, browser chrome stripped".  The revised `graphing-slope-intercept-screenshot.png` is 1536x1008.

**Comment by pixelzoom** [comment]
@KatieWoe pointed me to https://github.com/phetsims/tasks/issues/947, which documents the new size standard as 1536x1008.  So all is well, closing.
