### ISSUE TITLE
revise related materials for 1.1.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#23]
Graphing Slope-Intercept 1.1.0 will contain a number of UI changes, including phetsims/graphing-lines#91, phetsims/graphing-lines#92, phetsims/graphing-lines#94.  Related materials (teacher tips, activities, primer video,...) may need to be revised to reflect these changes.  

Screenshot updates are covered by #22.

This should be done reasonably close to the 1.1.0 release.

**Comment by pixelzoom** [comment]
@amanda-phet Heads up - RC testing for 1.0.0 release will start next week.

**Comment by amanda-phet** [comment]
Teacher tips are updated and ready to upload when the sim is published.

**Comment by pixelzoom** [comment]
@amanda-phet Since the game level icons were updated in phetsims/graphing-lines#113, are there any related materials that need to be updated?

**Comment by amanda-phet** [comment]
Thanks, just made the updates.

**Comment by pixelzoom** [comment]
@amanda-phet 1.1.0 has been published. You can publish revised materials.

**Comment by amanda-phet** [comment]
Done!
