### ISSUE TITLE
iOS 10 freeze

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-slope-intercept#27]
For https://github.com/phetsims/QA/issues/278
@lmulhall-phet  saw Graphing Slope-Intercept freeze on iOS 10 after playing with it for awhile.  He was unable to recreate while the device was tethered trying to see if there was an error.  I talked with @oliver-phet  today about how much we want to support iOS 10 moving forward, so it may be a good idea to talk with he and @ariel-phet  before pursuing this.
This device has given us some trouble, and it has been hard to determine if it is the device, or if there is a problem.  However, it should be noted that the problems on this device are normally poor performance and a crash that forces the page to reload.  This freezing behavior is not something I think I have seen, so it may still be worth looking at.
@lmulhall-phet please fill in any other details, such as screens it happened on, general actions you took, performance beforehand, etc. when you have the chance.

**Comment by KatieWoe** [comment]
- It has not.  Like I said, it has only really manifested as a crash that reloads the page or bad performance
- We do not.  Since Apple doesn't let you downgrade, or only upgrade a certain amount, we need a device they stopped supporting during the transition, which is only the iPad 4 and a few phones.
- Liam didn't mention it, but I think he was trying to reproduce the freeze in a tether, so he may not have gotten to it yet.  I'll grab the device and play with it for 10 minutes and get back to you.

**Comment by KatieWoe** [comment]
Update after playing with Graphing Lines for ~10 minutes.  I saw the crash and reload once during the game screen, but no other time and I did not see the freezing behavior.

**Comment by ariel-phet** [comment]
@pixelzoom @KatieWoe we are going to ignore this issue for the moment. Two rationales:

1. This test device does seems a bit suspect to me. @oliver-phet might look into getting a new iOS 10 test device. 

2. Looking at the numbers, we are probably going to drop iOS10 support when we publish the app. This OS accounts for a pretty small percentage of our usage.

**Comment by pixelzoom** [comment]
@KatieWoe In https://github.com/phetsims/QA/issues/286#issuecomment-463700773 and https://github.com/phetsims/QA/issues/287#issuecomment-463700919, you describe iOS 10 crashes with RC3.  I understand that PhET got a new iOS 10 test device.  Are those crashes with that new device, or with the original device that was used to report this issue?

**Comment by KatieWoe** [comment]
We did a comparison yesterday between the two devices and they didn't seem to be any different.

**Comment by pixelzoom** [comment]
Chris Malley [11:33 AM]
I understand that there was no difference in performance. Was there any difference in crashing behavior?

Kathryn Woessner [11:34 AM]
Liam did all the actual testing.  I don't think there was a difference from what he said.

Chris Malley [11:35 AM]
Is Liam around? Also need to know whether your recent reports were on the original device or the new device.

Kathryn Woessner [11:35 AM]
Original.  I'll slack him and ask. I'll let you know what I hear back

**Comment by pixelzoom** [comment]
Slack report from @rea-laura, re Graphing Lines 1.3.0-rc.4 (https://github.com/phetsims/QA/issues/290):

Laura Rea [12:23 PM]
Hi Chris, just wanted to let you know that I found occasional crashing behavior in the RC test for graphing lines. I only had it happen twice within about 45 mins, both times were with the stringTest=long query param. Katie doesn't think it's a problem, but we just wanted to make you aware of it!

Chris Malley [1:26 PM]
What platform?

Laura Rea [1:26 PM]
sorry, iOS 10

Chris Malley [1:26 PM]
Then I’m not worried :) Thanks for reporting!

Laura Rea [1:26 PM]
okay, great! no problem!

Chris Malley [1:28 PM]
Just to make sure… The crash was of the same nature as https://github.com/phetsims/graphing-slope-intercept/issues/27, correct?

Laura Rea [1:29 PM]
the crash was less of a "freeze" like this issue describes, more like an unexpected page refresh

**Comment by pixelzoom** [comment]
Unassigning since this is deferred until the next release cycle.

**Comment by pixelzoom** [comment]
According to https://phet.colorado.edu/en/help-center/running-sims, iOS10 is no longer a supported platform:

> iPad: iOS 12+ Safari

Closing.
