### ISSUE TITLE
update credits for 1.1.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#29]
Current credits are shown below. @amanda-phet @KatieWoe anything to add?

<img width="766" alt="screenshot_1042" src="https://user-images.githubusercontent.com/3046552/52663737-83ba4080-2ec4-11e9-98e6-ba60f5b21e81.png">

**Comment by KatieWoe** [comment]
Liam, Laura, Jacob, and myself should be added to QA

**Comment by pixelzoom** [comment]
Additions to QA credits have been completed.

**Comment by pixelzoom** [comment]
Additions to QA credits have been completed: 

<img width="758" alt="screenshot_1043" src="https://user-images.githubusercontent.com/3046552/52665166-24f6c600-2ec8-11e9-8dc8-01b28f75a7a3.png">

**Comment by amanda-phet** [comment]
Please add Megan Lai to graphic arts.

**Comment by pixelzoom** [comment]
Additions to Graphic Arts credits have been completed:

<img width="750" alt="screenshot_1048" src="https://user-images.githubusercontent.com/3046552/52676996-5e8bf900-2ee9-11e9-9ab1-0be7701f6812.png">

**Comment by pixelzoom** [comment]
Pending verification in 1.1.0-rc.3.

**Comment by pixelzoom** [comment]
To verify this issue, run the sim and compare to the screenshot in https://github.com/phetsims/graphing-slope-intercept/issues/29#issuecomment-462997809.

**Comment by KatieWoe** [comment]
Confirm 1.1.0-rc.3
