### ISSUE TITLE
Consider using PropertyFractionNode (common)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/graphing-slope-intercept#31]
Any sim that uses a fraction in a display might want to consider using (and modifying, if needed) the new fraction common code that was added due to https://github.com/phetsims/fractions-intro/issues/7 .

**Comment by pixelzoom** [comment]
graphing-slope-intercept is a derivative of graphing-lines.  Whatever decision is made in https://github.com/phetsims/graphing-lines/issues/130 will apply here.  So closing this issue.
