### ISSUE TITLE
No sound in Graphing Slope Intercept

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-slope-intercept#32]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For ES6 Testing. There is no sound in the master version of the sim. On published it seems to use vibe (has a mute/unmute button on the screen with sound before game starts). Graphing Lines uses tambo and it seems to work there. GSI does not have the vibe button described above, or a tambo control (a mute/unmute button on the nav bar for the whole sim).

**Visuals**
![nosoundatall](https://user-images.githubusercontent.com/41024075/75728132-2bf3a080-5ca4-11ea-9310-1c1e0d54bec4.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: Graphing Slope-Intercept
URL: http://phettest.colorado.edu/graphing-slope-intercept/graphing-slope-intercept_en.html?ea&brand=phet
Version: 1.2.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
This is really strange. graphing-slope-intercept gets all of its Game code from graphing-lines. All that it provides is a new set of challenges that consist only of slope-intercept challenges.

**Comment by pixelzoom** [comment]
Fixed in the above commit.

On 11/12/19, @jbphet added `"supportsSound": true` to graphing-lines/package.json.  He did not do the same for graphing-slope-intercept. I added `"supportsSound": true` to graphing-slope-intercept/package.json, ran grunt update, and sound is now working.

@KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Looks fixed in master.
