### ISSUE TITLE
name for the game screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#4]
@amanda-phet What do you want to name the game screen?  It's "Line Game" in Graphing Lines.

**Comment by pixelzoom** [comment]
... and do you want to use the same screen icon that's used in Graphing Lines?

**Comment by amanda-phet** [comment]
Line Game sounds good to me. 

Using all of the same icons seems like the way to go.

**Comment by pixelzoom** [comment]
Got it, done.
