### ISSUE TITLE
which rewards to show in game?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#6]
From the source code documentations, here are the rewards that are shown for each level in Graphings Lines. If you want to see these in action, run the sim with `?showReward`, and you'll see the reward at the end of each game, regardless of your score.

```
 * Level 1 = equations
 * Level 2 = graphs
 * Level 3 = point tools
 * Level 4 = smiley faces
 * Level 5 = paper airplanes
 * Level 6 = all of the above
```

How do you want to map these rewards to the 4 levels in Graphing Slope-Intercept?

**Comment by pixelzoom** [comment]
Here's a screenshot from the reward in level 6, which contains all of the items from the rewards for lower levels:

![screenshot_178](https://cloud.githubusercontent.com/assets/3046552/23776394/4e39e03c-04eb-11e7-93d7-4743c3c066e9.png)

**Comment by pixelzoom** [comment]
The equations that are shown in the reward are in both slope-intercept and point-slope form, selected randomly.  It will be a bit difficult (but not impossible) to turn off generation of the point-slope equations for the reward.  And if you want the "all of the above" behavior of level 6, we'll have to address that - if you think it matters in the reward.

**Comment by amanda-phet** [comment]
Let's do: 

Level 1: Graphs
Level 2: Point Tools
Level 3: Paper Airplanes
Level 4: Smiley Faces

**Comment by pixelzoom** [comment]
I made the reward configurable in Graphing Lines, and set up the desired rewards for each level in Graphing Slope-Intercept.  

Closing.
