### ISSUE TITLE
RandomChooser is flawed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#8]
In `GSIChallengeFactory1`, it's possible to run out of entries in `yInterceptArrays` (the set of y-intercepts) by the time we get to challenge 6, resulting in an assertion failure here:

```js
145  yIntercept = RandomChooser.chooseFromArrays( yInterceptArrays, yInterceptArrayIndices ); // required y-intercept
```

I'm not quite sure why this is happening. There are 2 sets of y-intercepts, and I only see 2 calls like this that remove an entire set of y-intercepts:

```js
RandomChooser.chooseFromArrays( yInterceptArrays, yInterceptArrayIndices )
```

**Comment by pixelzoom** [comment]
We have 2 sets of y-intercepts (negative and positive) like this:

```js
[ [ -6, -5, -4, -3, -2, -1 ], [ 1, 2, 3, 4 ] ]
```

All 6 of the challenges randomly choose a y-intercept from these, and the second set only contains 4.  So it's possible that we may exhaust the second set, leaving it as an empty array.  This was never a problem in Graphing Lines.   So I'll need to change the random chooser to remove the empty array.

**Comment by pixelzoom** [comment]
I confirmed that this is not a problem in Graphing Lines by putting adding this to `initChallenges` in `BaseGameModel`:

```js
      for ( var i = 0; i < 100000; i++ ) {
        console.log( 'i=' + i );
        this.challengeFactories[ level ].createChallenges( GLConstants.X_AXIS_RANGE, GLConstants.Y_AXIS_RANGE );
      }
```

**Comment by pixelzoom** [comment]
Fixing this would involve monkeying around with (or worse, replacing) the `RandomChooser` used in Graphing Lines.  I investigated - it feels a little precarious and is not at all straightforward.

@amanda-phet How would you feel about changing the sets of y-intercepts in level 1, from this:

> [ [ -6, -5, -4, -3, -2, -1 ], [ 1, 2, 3, 4 ] ]

to this:

> [ [ -6, -5, -4, -3, -2, -1 ], [ 1, 2, 3, 4, 5, 6 ] ]

That would ensure that we have enough y-intercepts for all 6 challenges.

Also note that the y-intercept sets in level 2 are:

> [ [ -10, -9, -8, -7, -6, -5, -4, -3, -2, -1 ], [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] ]

**Comment by pixelzoom** [comment]
Hmmm... Looks to me like we might have a similar problem for the sets of slopes in level 1:

```js
[ new Fraction( 3, 2 ), new Fraction( 4, 3 ), new Fraction( 5, 2 ), new Fraction( 5, 3 ) ],
[ new Fraction( 1, 2 ), new Fraction( 1, 3 ), new Fraction( 1, 4 ), new Fraction( 1, 5 ) ],
[ new Fraction( 2, 3 ), new Fraction( 3, 4 ), new Fraction( 3, 5 ), new Fraction( 2, 5 ) ]
```

So I think I need to bite the proverbial bullet and fix this in RandomChooser.

**Comment by pixelzoom** [comment]
@amanda-phet Regardless of how I fix this, we'll need to add some values to the y-intercepts in level 1.  Are you OK with expanding the range to [-6,6], as described in https://github.com/phetsims/graphing-slope-intercept/issues/8#issuecomment-286237247?

**Comment by amanda-phet** [comment]
The issue with expanding the y-intercept range to 6 is that if the selected slope is one of three from the first array such that the next point won't fit on the graph, the user will need to count backward, which we are trying to avoid for an introductory sim/game. 

We'd need to introduce some logic that does not allow that to happen. 

When it comes to the slope arrays I could come up with additional slopes to add to the arrays, but I'm not sure about the best way to go about the y-intercept problem.

**Comment by pixelzoom** [comment]
@amanda-phet I've revised the challenge factory approach in graphing-slopes. If you want to try master, be my guest, but it's been "lightly tested".   I did not need to change the y-intercept range in level 1, it's still [-6,4].  

More work to come...

**Comment by pixelzoom** [comment]
Btw... The new approach does away with RandomChooser entirely.

**Comment by pixelzoom** [comment]
RandomChooser replace by ValuePool.  Lightly tested, full regression test and comparison to design spec still needs to be done.

**Comment by pixelzoom** [comment]
@amanda-phet Here's a dev version for your verification, challenges should match the specification in the design document:  

http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-dev.5/graphing-slope-intercept_en.html?showAnswers&shuffle=false

No changes to the intercept ranges were required. It's still [-6,4] in level 1, and [-10,10] in levels 2-4 (zero excluded in all cases).

A couple of changes to note:
• The `shuffleChallenges` query parameter has been renamed `shuffle`. So use `shuffle=false` to keep challenges in same order as they are described in the design document.
• In addition to showing the answers, the `showAnswers` query parameter also shows Skip/Replay button and description of challenge.  This was previously the responsibility of `gameDebug` query parameter, which no longer exists.
• Skip/Replay button is now red and a bit larger.

**Comment by amanda-phet** [comment]
The challenges look good to me!
